apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: podinfo
    release: observability-kube-prometheus-stack
  name: podinfo
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo
  endpoints:
    - port: http
      scrapeTimeout: 3s
      scheme: http
      path: "/metrics"
      interval: "5s"
