apiVersion: v1
data:
  values: |
    cluster:
      domain: ${cluster_domain}
kind: ConfigMap
metadata:
  name: flux-app-user-values
  namespace: ${cluster_id}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: flux-app
  namespace: ${cluster_id}
spec:
  catalog: giantswarm-test
  kubeConfig:
    context:
      name: ${cluster_id}
    inCluster: false
    secret:
      name: ${cluster_id}-kubeconfig
      namespace: ${cluster_id}
  name: flux-app
  namespace: flux-app
  userConfig:
    configMap:
      name: flux-app-user-values
      namespace: ${cluster_id}
  version: 0.10.0-20e20882fe36dfda3de0c609b91cf3492ac172b6
