apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubepad-2
  labels:
    app: nginx-2
    k8s-minipad/enabled: "true"
    LAUNCHPAD_ENABLE: "true"
    LAUNCHPAD_COLOR: BLUE
    LAUNCHPAD_ROW: "2"
    lab: cloudkoffer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 10
