apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubepad-3
  labels:
    app: nginx-3
    k8s-minipad/enabled: "true"
    LAUNCHPAD_ENABLE: "true"
    LAUNCHPAD_COLOR: GREEN
    LAUNCHPAD_ROW: "3"
    lab: cloudkoffer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 10
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: default
spec:
  rules:
  - host: nginx.cloudkoffer
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
