apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepad-4
  labels:
    app: nginx-4
    k8s-minipad/enabled: "true"
    LAUNCHPAD_ENABLE: "true"
    LAUNCHPAD_COLOR: LIGHT_GREEN
    LAUNCHPAD_ROW: "4"
    lab: cloudkoffer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-4
  template:
    metadata:
      labels:
        app: nginx-4
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 10
