apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepad-6
  labels:
    app: nginx-6
    k8s-minipad/enabled: "true"
    LAUNCHPAD_ENABLE: "true"
    LAUNCHPAD_COLOR: YELLOW
    LAUNCHPAD_ROW: "6"
    lab: cloudkoffer
spec:
  replicas: 6
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-6
  template:
    metadata:
      labels:
        app: nginx-6
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 10
